#!/usr/bin/env python3
"""Build a 3D showcase of what each workbench tool does, on real public proteins.

Measurement colors come from real runs; identity colors distinguish proteins. Each panel
pairs one public PDB or AlphaFold entry from qualification panel v2 with the
per-residue output its tool actually wrote during that panel's execution, and
states that case's recorded gate result. Nothing private is read: the inputs are
public entries acquired under the panel's SOURCE_LOCK and the outputs are the
committed execution evidence.

SF-CSA instead displays two pairs of checksum-verified predicted models and
comparison values from the frozen panel manifest, with primary literature
annotations kept separate. It makes no new execution or gate-pass claim.

The state panel also derives a new pairwise alignment, per-residue displacement
and endpoint angles from the locked ABL coordinates and residue maps. These
teaching measurements are distinct from the recorded classification results.

The result is one self-contained HTML file -- 3Dmol.js (BSD-3, notice included)
and every structure are embedded -- so it opens offline and loads nothing from
the network. It is written under build/, which is gitignored: building it does
not publish it.

Requires the panel's sources to have been acquired (acquire_sources.py), NumPy
and Biopython for endpoint geometry; the built page itself needs nothing.

Usage:  python tools/build_3d_showcase.py [--out build/showcase-3d/index.html]
"""
from __future__ import annotations

import argparse
import csv
import html
import hashlib
import importlib.util
import json
import os
import pathlib
import shlex
import statistics
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
Q = ROOT / "evidence" / "benchmarks" / "qualification-v2"
R = Q / "results"
S = Q / "sources"
VENDOR = ROOT / "software" / "structural-workbench" / "src" / "yauvi_structural_workbench" / "ui" / "vendor"


def find_source(name: str) -> pathlib.Path:
    hits = sorted(S.rglob(name))
    if not hits:
        sys.exit(f"missing acquired source {name!r}; run the panel's acquire_sources.py first")
    return hits[0]


def rows(path: pathlib.Path) -> list[dict]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def case_passed(execution_dir: str, needle: str) -> bool | None:
    status = R / execution_dir / "EXECUTION_STATUS.json"
    if not status.exists():
        return None
    for case in json.loads(status.read_text()).get("cases", []):
        if needle in case.get("record_id", ""):
            return case.get("passed")
    return None


def ca_coords(text: str, fmt: str) -> dict[str, tuple[float, float, float]]:
    """chain:resi -> CA position, from PDB or the mmCIF _atom_site loop (auth numbering)."""
    out: dict[str, tuple[float, float, float]] = {}
    if fmt == "pdb":
        for line in text.splitlines():
            if line.startswith("ATOM") and line[12:16].strip() == "CA":
                out.setdefault(f"{line[21]}:{line[22:26].strip()}",
                               (float(line[30:38]), float(line[38:46]), float(line[46:54])))
        return out
    fields, rows_, in_loop = [], [], False
    for line in text.splitlines():
        if line.startswith("_atom_site."):
            fields.append(line.split(".", 1)[1].strip()); in_loop = True; continue
        if in_loop:
            if not line.strip() or line.startswith(("#", "loop_", "_")):
                if rows_: break
                continue
            rows_.append(line.split())
    ix = {f: i for i, f in enumerate(fields)}
    for r in rows_:
        if len(r) < len(fields) or r[ix["label_atom_id"]] != "CA" or r[ix["group_PDB"]] != "ATOM":
            continue
        key = f"{r[ix.get('auth_asym_id', ix['label_asym_id'])]}:{r[ix.get('auth_seq_id', ix['label_seq_id'])]}"
        out.setdefault(key, (float(r[ix["Cartn_x"]]), float(r[ix["Cartn_y"]]), float(r[ix["Cartn_z"]])))
    return out


def one(path_glob: str) -> pathlib.Path:
    hits = sorted(R.glob(path_glob))
    if not hits:
        sys.exit(f"missing result {path_glob}")
    return hits[0]


# ------------------------------------------------------------------- commands
# The commands shown on the page are generated by the qualification executor's own
# command builders -- the same code that produced every result on the page -- so
# they cannot drift from what actually ran.
_spec = importlib.util.spec_from_file_location("qualification_execution", Q / "run_execution.py")
_EXEC = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_EXEC)
_RECORDS: dict[str, dict] = {}


def _index_records(node) -> None:
    if isinstance(node, dict):
        if "record_id" in node and "expected_result" in node:
            _RECORDS[node["record_id"]] = node
        for v in node.values():
            _index_records(v)
    elif isinstance(node, list):
        for v in node:
            _index_records(v)


_index_records(json.loads((Q / "PANEL_MANIFEST.json").read_text()))


def _portable(argv: list[str]) -> str:
    """Render argv relative to the panel directory. Refuse any absolute path."""
    base = str(Q.resolve()) + os.sep
    out = []
    for token in argv:
        token = str(token).replace(base, "")
        if token.startswith(("/", "~")) or str(pathlib.Path.home()) in token:
            sys.exit(f"refusing to publish an absolute path in a command: {token}")
        out.append(shlex.quote(token))
    return " ".join(out)


def commands_for(record_id: str, workflow: str, out_name: str) -> list[str]:
    inv = dict(_RECORDS[record_id]["expected_result"]["invocation"])
    lines = []
    upstream = inv.pop("upstream", None)
    if upstream:
        up_wf = upstream.get("workflow", "structure_qc")
        eng = _EXEC.ENGINES[up_wf]
        lines.append(_portable(eng["build_cmd"](upstream, eng["cli"], pathlib.Path("qc"))))
        inv["manifest"] = f"qc/{eng['evidence']}"
    eng = _EXEC.ENGINES[workflow]
    lines.append(_portable(eng["build_cmd"](inv, eng["cli"], pathlib.Path(out_name))))
    return lines


# --------------------------------------------------------------------- panels
def structqc() -> dict:
    case = one("execution-structqc/v2-structqc-alphafold-dev-P00698")
    bands = [(90, "#0053D6", "very high (≥ 90)"), (70, "#65CBF3", "confident (70–90)"),
             (50, "#FFDB13", "low (50–70)"), (0, "#FF7D45", "very low (< 50)")]
    cmap, values = {}, []
    for r in rows(case / "RESIDUE_QUALITY.tsv"):
        try:
            v = float(r["plddt"])
        except (KeyError, ValueError):
            continue
        values.append(v)
        cmap[f"{r['chain_id']}:{r['auth_seq_id']}"] = next(c for t, c, _ in bands if v >= t)
    counts = {label: sum(1 for v in values if lo <= v < hi)
              for (lo, _, label), hi in zip(bands, [101, 90, 70, 50])}
    return {
        "id": "structqc", "tool": "structqc", "title": "Coordinate trust",
        "question": "Can I trust these coordinates?",
        "protein": "Hen egg-white lysozyme — AlphaFold model", "entry": "AF-P00698-F1",
        "link": "https://alphafold.ebi.ac.uk/entry/P00698",
        "viewers": [{"label": "", "fmt": "cif", "structure": find_source("AF-P00698-F1-model_v6.cif").read_text(),
                     "cmap": cmap, "style": "cartoon"}],
        "legend": [(c, l) for _, c, l in bands],
        "reported": [
            f"{len(values)} residues scored, mean pLDDT {statistics.mean(values):.1f}",
            *[f"{n} residues {label}" for label, n in counts.items() if n],
            "Coverage is bound to a declared reference sequence, so a missing or extra "
            "residue is reported, never silently accepted.",
        ],
        "passed": case_passed("execution-structqc", "P00698"),
        "scope": "Qualified scope: coordinate provenance and validation (X-ray, cryo-EM, NMR, AlphaFold strata).",
        "limit": "Reports coordinate and provenance quality only — not whether the fold is native or the protein functional.",
        "commands": commands_for("v2-structqc-alphafold-dev-P00698", "structure_qc", "qc"),
    }


def membrane() -> dict:
    case = one("execution-membrane/v2-membrane-beta_barrel-held-2MPR")
    zones = {"extracellular": "#2E86AB", "extracellular_interface": "#8ECAE6",
             "hydrophobic_core": "#F4A261", "periplasmic_interface": "#C9A7B7", "periplasmic": "#6D597A"}
    cmap = {f"{r['chain']}:{r['resid']}": zones.get(r["zone"], "#cccccc")
            for r in rows(case / "RESIDUE_ORIENTATION.tsv")}
    summary = json.loads((case / "MEMBRANE_ORIENTATION.json").read_text())["summary"]
    pdb = (case / "ORIENTED_STRUCTURE.pdb").read_text()
    xs, ys = [], []
    for line in pdb.splitlines():
        if line.startswith(("ATOM", "HETATM")):
            xs.append(float(line[30:38])); ys.append(float(line[38:46]))
    return {
        "id": "membrane", "tool": "memorient", "title": "Membrane sidedness",
        "question": "Which side of the membrane does my protein face?",
        "protein": "Maltoporin (LamB) trimer — outer-membrane β-barrel", "entry": "PDB 2MPR",
        "link": "https://www.rcsb.org/structure/2MPR",
        "viewers": [{"label": "", "fmt": "pdb", "structure": pdb, "cmap": cmap, "style": "cartoon",
                     "membrane": {"half": summary["half_thickness"], "cx": (min(xs) + max(xs)) / 2,
                                  "cy": (min(ys) + max(ys)) / 2,
                                  "span": max(max(xs) - min(xs), max(ys) - min(ys)) + 16}}],
        "legend": [(c, z.replace("_", " ")) for z, c in zones.items()] + [("#E9C46A", "fitted membrane planes")],
        "reported": [
            f"Membrane half-thickness {summary['half_thickness']:.2f} Å; {summary['n_embedded']} residues embedded",
            f"{summary['n_extracellular']} residues placed extracellular",
            f"Placement confidence {summary['confidence']}, extracellular-side sign confidence {summary['ec_sign_confidence']}",
            "The planes are the tool's own fitted membrane: the embedded core spans z = −11.8 to +11.7 Å.",
        ],
        "passed": case_passed("execution-membrane", "2MPR"),
        "scope": "Research-only. Mark 1 makes no accuracy claim for membrane orientation: 5 of 16 β-barrel cases pass its accuracy gate, and 2MPR is one of the five.",
        "limit": "A geometric placement, not a measured topology.",
        "commands": commands_for("v2-membrane-beta_barrel-held-2MPR", "membrane_orientation", "membrane"),
    }


def state() -> dict:
    spec = importlib.util.spec_from_file_location("showcase_state_motion", ROOT / "tools/showcase_state_motion.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    motion = module.build_motion(Q)
    def motion_color(distance):
        return "#457B9D" if distance < 2 else "#E9C46A" if distance < 5 else "#F4A261" if distance < 10 else "#E63946"
    cmap = {f"A:{r['position']}": motion_color(r["displacement"]) for r in motion["residues"]}
    viewers, reported, passed = [], [], []
    for name, pdb_id, color in (("active", "2GQG", "#2A9D8F"), ("inactive", "2HYY", "#7B5EA7")):
        case = one(f"execution-abl/v2-stateatlas-{name}-held_out-{pdb_id}")
        m = rows(next(case.rglob("FRAME_METRICS.tsv")))[-1]
        viewers.append({"label": f"{pdb_id} — {m['call'].replace('_', '-')} · colored by endpoint displacement", "fmt": "pdb",
                        "structure": motion[f"{name}_pdb"], "cmap": cmap, "zoom": 0.7,
                        "uniform": color, "style": "cartoon"})
        reported.append(f"{pdb_id}: {m['call'].replace('_', '-')}, closest reference {m['best_reference']} "
                        f"at {float(m['best_rmsd_A']):.2f} Å (margin {float(m['margin_A']):.2f} Å)")
        passed.append(case_passed("execution-abl", pdb_id))
    return {
        "id": "state", "tool": "state-atlas", "title": "Conformational state",
        "question": "Which known conformation does my structure resemble?",
        "protein": "ABL kinase — active (2GQG) and inactive (2HYY), both held out", "entry": "PDB 2GQG · 2HYY",
        "link": "https://www.rcsb.org/structure/2HYY",
        "viewers": viewers,
        "motion": motion,
        "legend": [("#457B9D", "Cα displacement <2 Å"), ("#E9C46A", "2–5 Å"), ("#F4A261", "5–10 Å"), ("#E63946", "≥10 Å")],
        "reported": reported + ["Both are held-out entries the references were not built from, and both are called correctly.",
                                  f"New endpoint comparison: {motion['mapped_count']}/254 equivalent residues, global Cα RMSD {motion['rmsd']:.2f} Å. This pairwise value is distinct from the reference-classification RMSDs above."],
        "passed": all(passed) if all(p is not None for p in passed) else None,
        "scope": "Qualified scope: ABL-family kinases (human P00519) only.",
        "limit": "Resemblance to reference states — not activity in a cell. Both structures are inhibitor-bound under different conditions. Interpolated coordinates are illustrations, not measured intermediates; bond lengths, sterics and energies are not preserved. The qualification badge covers the original state calls, not the new motion illustration.",
        "commands": commands_for("v2-stateatlas-active-held_out-2GQG", "conformational_state", "state"),
    }


def state_motion_html(p: dict) -> str:
    if "motion" not in p:
        return ""
    m, e = p["motion"], html.escape
    regions = "".join(f'<option value="{r["id"]}">{e(r["label"])}</option>' for r in m["regions"])
    residues = "".join(f'<option value="{r["position"]}"{" selected" if r["position"] == 382 else ""}>{r["resname"]} {r["position"]} · {r["displacement"]:.2f} Å</option>' for r in m["residues"])
    largest = sorted(m["residues"], key=lambda r: -r["displacement"])[:5]
    movers = ", ".join(f'{r["resname"]}{r["position"]} ({r["displacement"]:.1f} Å)' for r in largest)
    return f'''<div class="motion-box"><h3>See which amino acids change position</h3>
<p>The activation loop rearranges around the DFG motif (Asp381–Phe382–Gly383). Compare the actual endpoints, then use the slider to follow corresponding Cα positions.</p>
<div class="motion-controls"><label>Region <select id="state-motion-region">{regions}</select></label>
<label>Residue <select id="state-motion-residue">{residues}</select></label>
<button type="button" id="state-motion-reset">Reset close-up</button></div>
<label class="motion-slider">Active-like → inactive-like <input id="state-motion-slider" type="range" min="0" max="100" value="0" aria-label="Interpolate between active-like and inactive-like endpoints"></label>
<div class="motion-controls"><button type="button" id="state-motion-play" aria-pressed="false">Play illustrative motion</button><button type="button" id="state-motion-export">Download geometry and provenance</button></div>
<div id="state-motion-view" class="viewer motion-view"></div>
<p class="hint">Teal: active-like endpoint (2GQG, dasatinib). Purple: inactive-like endpoint (2HYY, imatinib). Amber spheres and guide lines: interpolated Cα trace, not chemical bonds. Red arrow: selected residue's endpoint displacement. Sticks: its actual endpoint atoms.</p>
<p id="state-motion-status" role="status">Active-like endpoint · 2GQG</p><p id="state-region-detail"></p>
<p><strong>This slider is not a simulation.</strong> Intermediate shapes are straight-line interpolation, not an observed or energy-validated transition. Endpoint angles below do not change with the slider.</p>
<h3>Selected residue: measured endpoint geometry</h3><p id="state-motion-detail"></p>
<div class="motion-table"><table><thead><tr><th>Measurement</th><th>Active-like</th><th>Inactive-like</th><th>Change</th></tr></thead><tbody id="state-angle-body"></tbody></table></div>
<p class="hint">φ and ψ describe backbone rotations; χ1 describes a side-chain rotation. These torsions differ from a bond angle. Torsion changes use the shortest signed circular difference. Missing or ambiguous atoms give “unavailable”. Crystallographic geometry is not a precision claim about dynamics.</p>
<details><summary>Alignment, largest movements and research evidence</summary>
<p>{e(m["method"])} {m["mapped_count"]}/254 residues used; excluded positions: {e(', '.join(map(str,m['excluded_positions'])))}. Position 275 is absent from the inactive query map; 393 is a modified phosphotyrosine in 2GQG and omitted by its standard-residue map. Neither gap is bridged.</p>
<p>Largest Cα displacements under this fit: {e(movers)}. These are coordinate differences, not motion amplitudes measured over time. The displayed fit includes the flexible loop; another alignment mask would change the displacements.</p>
<p><a href="https://doi.org/10.1158/0008-5472.CAN-05-4187" target="_blank" rel="noopener">Tokarski et al. 2006: activated ABL–dasatinib structure</a> · <a href="https://www.rcsb.org/structure/2HYY" target="_blank" rel="noopener">2HYY: ABL–imatinib structure and primary citation</a></p>
<p>Source coordinates and exact residue maps are checked against the original run's SHA-256 values. Download includes per-residue Cα displacements, endpoint angles, transformation and source hashes. No frozen qualification results are modified.</p></details></div>'''


def site() -> dict:
    case = one("execution-sitecontext/v2-sitecontext-nucleophile_or_covalent-dev-1BTL")
    roles = {"nucleophile": "#E63946", "acid_base": "#F4A261", "unspecified": "#457B9D"}
    names = {"S": "Ser", "K": "Lys", "E": "Glu", "A": "Ala", "D": "Asp", "H": "His", "C": "Cys"}
    picked: dict[str, dict] = {}
    for r in rows(case / "SITE_RESIDUES.tsv"):
        key = f"{r['chain_id']}:{r['auth_seq_id']}"
        if key not in picked or r["role"] != "unspecified":
            picked[key] = r
    structure = find_source("1BTL.cif").read_text()
    ca = ca_coords(structure, "cif")
    highlights = [{"chain": r["chain_id"], "resi": int(r["auth_seq_id"]), "color": roles.get(r["role"], "#457B9D"),
                   "label": f"{names.get(r['observed_residue'], r['observed_residue'])}{r['auth_seq_id']}",
                   "at": ca.get(f"{r['chain_id']}:{r['auth_seq_id']}")}
                  for r in picked.values()]
    return {
        "id": "site", "tool": "site-context", "title": "Functional sites",
        "question": "Are the functional residues structurally intact?",
        "protein": "TEM-1 β-lactamase — the enzyme behind penicillin resistance", "entry": "PDB 1BTL",
        "link": "https://www.rcsb.org/structure/1BTL",
        "viewers": [{"label": "", "fmt": "cif", "structure": structure,
                     "cmap": {}, "uniform": "#D9D9D9", "style": "cartoon", "highlights": highlights,
                     "focus": [{"chain": h["chain"], "resi": h["resi"]} for h in highlights]}],
        "legend": [(c, r.replace("_", "/")) for r, c in roles.items()],
        "reported": [f"{h['label']} — {picked[f'{h['chain']}:{h['resi']}']['role'].replace('_', '/')}, "
                     f"{picked[f'{h['chain']}:{h['resi']}']['state'].replace('_', ' ')}" for h in highlights]
                    + ["Every declared catalytic residue is present and compatible with its role."],
        "passed": case_passed("execution-sitecontext", "1BTL"),
        "scope": "Qualified scope: curated functional-site mapping (M-CSA annotations).",
        "limit": "Structural presence and role compatibility — not measured catalysis.",
        "commands": commands_for("v2-sitecontext-nucleophile_or_covalent-dev-1BTL", "functional_site_state", "site"),
    }


def assembly() -> dict:
    case = one("execution-assembly/v2-assembly-tetramer-dev-4HHB")
    chains = {"A": ("#E76F51", "α1"), "B": ("#2A9D8F", "β1"), "C": ("#F4A261", "α2"), "D": ("#264653", "β2")}
    contacts = rows(case / "INTERFACES.tsv")
    by_pair: dict[str, int] = {}
    highlights, seen = [], set()
    for r in contacts:
        by_pair[f"{r['subject_chain']}–{r['partner_chain']}"] = by_pair.get(f"{r['subject_chain']}–{r['partner_chain']}", 0) + 1
        key = (r["subject_chain"], r["subject_resseq"])
        if key not in seen:
            seen.add(key)
            highlights.append({"chain": r["subject_chain"], "resi": int(r["subject_resseq"]),
                               "color": "#FFD166", "label": ""})
    return {
        "id": "assembly", "tool": "assembly-context", "title": "Assembly interfaces",
        "question": "Which residues form the oligomer interface?",
        "protein": "Human haemoglobin — α2β2 tetramer", "entry": "PDB 4HHB",
        "link": "https://www.rcsb.org/structure/4HHB",
        "viewers": [{"label": "", "fmt": "cif", "structure": find_source("4HHB.cif").read_text(),
                     "cmap": {}, "by_chain": {c: v[0] for c, v in chains.items()}, "style": "cartoon",
                     "highlights": highlights, "hetero": True}],
        "legend": [(v[0], f"chain {c} ({v[1]})") for c, v in chains.items()] + [("#FFD166", "interface residues on chain A")],
        "reported": [f"{len(contacts)} residue contacts from chain A, {len(seen)} distinct interface residues"]
                    + [f"{pair}: {n} contacts" for pair, n in sorted(by_pair.items(), key=lambda kv: -kv[1])]
                    + ["Stoichiometry matches the deposited biological assembly (A/B/C/D)."],
        "passed": case_passed("execution-assembly", "4HHB"),
        "scope": "Qualified scope: deposited biological assemblies.",
        "limit": "Geometric contacts in the deposited assembly — not binding affinity.",
        "commands": commands_for("v2-assembly-tetramer-dev-4HHB", "assembly_interface", "assembly"),
    }


def sfcsa() -> dict:
    cases = json.loads((ROOT / "yauvi-structural-workbench/docs/SF_CSA_SHOWCASE_CASES.json").read_text())
    viewers, reported, studies = [], [], []
    for case in cases["cases"]:
        record = _RECORDS[case["record_id"]]
        expected = record["expected_result"]
        pair = record["pair"]
        for side, artifact, checksum, color in (
            ("query", "artifact", "checksum", "#2A9D8F"),
            ("target", "target_artifact", "target_checksum", "#E76F51"),
        ):
            source = Q / record[artifact]
            payload = source.read_bytes()
            if hashlib.sha256(payload).hexdigest() != record[checksum]:
                raise ValueError(f"SF-CSA showcase source checksum mismatch: {record[artifact]}")
            viewers.append({"label": f"{case[side].split(' (')[0]} · {pair[side + '_accession']} · AlphaFold",
                            "fmt": "pdb", "structure": payload.decode(), "cmap": {}, "uniform": color, "zoom": 0.65})
        leg = expected["structural_leg"]
        reported.append(f"{case['short_name']}: recorded aligned TM-score {float(leg['aligned_tm_score']):.4f}; "
                        f"query/target coverage {float(leg['query_coverage']):.1%}/{float(leg['target_coverage']):.1%}; "
                        f"RMSD {float(leg['rmsd']):.3f} Å. Label: {expected['judgment']['function_classification']}.")
        seq = expected["sequence_leg"]
        reported.append(f"{case['short_name']} sequence leg: " + (
            "no retained pairwise sequence comparison; absence of a row is not absence of homology."
            if "sequence_comparison" in expected["missing_evidence"] else
            f"{seq['percent_identity']}% identity; {seq['query_coverage_hsp']}% query HSP coverage; "
            f"{seq['orthology_status']} (not reciprocal-best-hit support)."))
        studies.append(case)
    return {
        "id": "sfcsa", "tool": "sf-csa", "title": "Cross-proteome comparison",
        "question": "When does a similar fold support a similar function across species?",
        "protein": "Two case studies · two fold spaces · four public protein models",
        "entry": "qualification v2, frozen comparison records",
        "link": "", "viewers": viewers,
        "legend": [("#2A9D8F", "query identity"), ("#E76F51", "comparison identity")],
        "studies": studies, "functional_analogy": cases["functional_analogy"],
        "reported": reported,
        "passed": None,
        "badge_text": "Frozen comparison; no fresh execution check",
        "view_note": "Each row is one fold family: ferredoxin-like above, OB-fold below. These are predicted monomers, independently centered, not an aligned overlay. Colors identify proteins.",
        "command_note": "Reproduction command generated from the qualification executor. Requires locked sources, Foldseek and DIAMOND. Replace the output directory with a fresh path outside the publication/source tree. The values above are frozen records, not a new run.",
        "scope": "Values read from PANEL_MANIFEST.json expected_result records; this showcase build does not rerun SF-CSA or verify current CI. Models are checksum-checked and independently centered, not superposed. Colors identify proteins, not function or confidence.",
        "limit": "These are homologous-family comparisons, not proof of convergent evolution or interchangeable function. The panel's no-false-promotion bound is definitional (Finding 7); neither pair establishes probable_same_function through reciprocal-best-hit evidence.",
        "commands": commands_for(next(r for r, v in _RECORDS.items() if "queries" in v["expected_result"].get("invocation", {})), "sf_csa", "release"),
    }


def sfcsa_research(p: dict) -> str:
    if not p.get("studies"):
        return ""
    e = html.escape
    blocks = ['<h3>Two case studies, two fold spaces</h3>']
    for case in p["studies"]:
        refs = " · ".join(f'<a href="{e(r["url"])}" target="_blank" rel="noopener">{e(r["label"])}</a>' for r in case["references"])
        blocks.append(f'<article class="use"><b>{e(case["short_name"])} — {e(case["fold"])}</b>'
                      f'<p>{e(case["query"])} ↔ {e(case["target"])}</p>'
                      f'<p><strong>Research supports:</strong> {e(case["function"])}</p>'
                      f'<p><strong>Limit:</strong> {e(case["limit"])}</p>'
                      f'<p><strong>Same-fold counterexample:</strong> {e(case["counterexample"])}</p>'
                      f'<p class="hint">{refs}</p></article>')
    analogy = p["functional_analogy"]
    blocks.append(f'<article class="use"><b>Functional analogy across different folds</b>'
                  f'<p>{e(analogy["text"])}</p><p class="hint">Literature example only; not an executed SF-CSA result here. '
                  f'<a href="{e(analogy["url"])}" target="_blank" rel="noopener">Primary research</a></p></article>')
    return "".join(blocks)


# How each tool gets its answer, and what that answer is for. Wording follows
# yauvi-structural-workbench/docs/workflows.md; keep the two in step.
HOW = {
    "structqc": {
        "how": ["Reads the coordinate file you supply: PDB or mmCIF, experimental or AlphaFold",
                "Maps every residue to a declared reference sequence",
                "Imports model confidence (pLDDT, PAE) or experimental validation where it exists",
                "Inventories models, chains, numbering, missing atoms and provenance"],
        "gives": ["Which residues can be trusted before anything else uses them",
                  "STRUCTURE_EVIDENCE.json, the checked input every other tool reads",
                  "Exactly which residues are missing or unmapped"]},
    "membrane": {
        "how": ["Starts from structqc's checked coordinates",
                "For a beta-barrel, fits the barrel axis and places a membrane slab along it",
                "For an alpha-helical protein, requires checksum-bound transmembrane spans",
                "Labels each residue: in the membrane, or on either face"],
        "gives": ["Which residues face out, sit in the membrane, or face in",
                  "An oriented structure file to reuse downstream",
                  "An explicit 'unresolved' when sidedness is not supported (experimental path)"]},
    "state": {
        "how": ["Starts from structqc's checked coordinates",
                "Aligns to at least two independently supported experimental references per state",
                "Aligns on the declared domain only, then applies that transform to the whole structure",
                "Reports RMSD, RMSF, clustering and state populations"],
        "gives": ["Which known conformation the structure most resembles, and by how much",
                  "The distance to every reference, so the call can be checked",
                  "A resemblance label, never an activity claim"]},
    "site": {
        "how": ["Starts from structqc's checked coordinates",
                "Takes the declared residues, roles, ligands, metals and cofactors",
                "Maps each one to exact coordinates in the structure",
                "Keeps UniProt, M-CSA, observed chemistry and pocket predictions as separate evidence"],
        "gives": ["Whether the functional residues are present and structurally intact",
                  "Which source each piece of site evidence came from",
                  "Residues that could not be mapped, listed rather than dropped"]},
    "assembly": {
        "how": ["Starts from structqc's checked coordinates",
                "Reads the isolated chain and the declared biological assembly",
                "Measures contacts, interface residues, solvent-accessible surface and burial",
                "Checks the chains present against the expected stoichiometry"],
        "gives": ["Which residues form the interface with partner chains",
                  "How much surface is buried when the assembly forms",
                  "A lower bound, flagged as such, when the assembly is incomplete"]},
    "sfcsa": {
        "how": ["Runs checksum-pinned search legs: Foldseek for structure, DIAMOND for sequence",
                "Searches whole reference proteomes",
                "Classifies each hit: exact protein, homolog, shared fold, analogy, or unresolved"],
        "gives": ["Which proteins across proteomes share this structure",
                  "What kind of relationship each hit has",
                  "No function is transferred from similarity automatically"]},
}


# ------------------------------------------------------------------------ page
PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>YAUVI Workbench — what each tool does</title>
<style>
:root{--bg:#fbfaf7;--panel:#ffffff;--ink:#1d1d1f;--muted:#5f6368;--line:#e6e2da;--accent:#2a6f97;--ok:#2a9d8f;--view:#ffffff}
@media (prefers-color-scheme:dark){:root{--bg:#141416;--panel:#1d1e21;--ink:#ececec;--muted:#a3a3a8;--line:#2e3035;--accent:#8ecae6;--ok:#57cc99;--view:#101113}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,sans-serif}
header{padding:28px 24px 8px;max-width:1240px;margin:0 auto}h1{font-size:26px;margin:0 0 6px;letter-spacing:-.01em}
.lede{color:var(--muted);max-width:820px;margin:0}.note{display:inline-block;margin-top:12px;padding:6px 10px;border:1px solid var(--line);border-radius:8px;font-size:13px;color:var(--muted)}
main{max-width:1240px;margin:0 auto;padding:16px 24px 40px;display:grid;grid-template-columns:260px 1fr;gap:20px}
nav{display:flex;flex-direction:column;gap:8px}nav button{all:unset;cursor:pointer;padding:12px 14px;border:1px solid var(--line);border-radius:12px;background:var(--panel)}
nav button[aria-selected=true]{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)}nav .t{font-weight:600}nav .q{font-size:13px;color:var(--muted)}
nav button:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
section.panel{display:none;background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:20px}section.panel.on{display:block}
.q2{font-size:21px;font-weight:650;margin:0 0 2px}.who{color:var(--muted);margin:0 0 14px}.who a{color:var(--accent)}
.grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(0,1fr);gap:18px}.views{display:grid;gap:10px}.views.two{grid-template-columns:1fr 1fr}
.vwrap{border:1px solid var(--line);border-radius:12px;overflow:hidden;background:var(--view)}.vwrap .cap{font-size:13px;padding:6px 10px;border-bottom:1px solid var(--line);color:var(--muted)}
.viewer{position:relative;width:100%;height:440px}.views.two .viewer{height:380px}
h3{font-size:13px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin:16px 0 6px}h3:first-child{margin-top:0}
ul{margin:0;padding-left:18px}li{margin:3px 0}.legend{display:flex;flex-wrap:wrap;gap:6px 14px;font-size:13px}.sw{display:inline-block;width:12px;height:12px;border-radius:3px;margin-right:6px;vertical-align:-1px;border:1px solid rgba(0,0,0,.15)}
.badge{display:inline-block;padding:3px 9px;border-radius:999px;font-size:12px;font-weight:600;border:1px solid var(--line)}.badge.ok{color:var(--ok);border-color:var(--ok)}
code{display:block;white-space:pre-wrap;word-break:break-all;background:var(--bg);border:1px solid var(--line);border-radius:8px;padding:8px 10px;font-size:12.5px}
.steps{margin:0;padding:0;list-style:none;counter-reset:s;display:grid;gap:6px}.steps li{counter-increment:s;display:flex;gap:10px;margin:0;font-size:13.5px}.steps li:before{content:counter(s);flex:none;width:22px;height:22px;border-radius:50%;background:var(--accent);color:var(--panel);font-size:12px;font-weight:700;display:grid;place-items:center}
.use{border:1px solid var(--line);border-radius:10px;padding:10px 12px;margin:0 0 8px;font-size:13.5px}.use b{display:block}.use .hint{margin-top:4px}
.motion-box{border:1px solid var(--line);border-radius:12px;padding:16px;margin:16px 0 24px}.motion-controls{display:flex;gap:12px;flex-wrap:wrap;align-items:end}.motion-controls label{display:grid;gap:4px;font-size:13px}.motion-controls select,.motion-controls button{font:inherit;background:var(--panel);color:var(--ink);border:1px solid var(--line);border-radius:7px;padding:8px}.motion-view{height:440px;margin-top:12px;border:1px solid var(--line);border-radius:10px}.motion-slider{display:grid;gap:6px}.motion-slider input{width:100%}.motion-table{overflow-x:auto}.motion-table table{width:100%;border-collapse:collapse;font-size:13px}.motion-table th,.motion-table td{text-align:left;padding:8px;border-bottom:1px solid var(--line)}details summary{cursor:pointer;color:var(--accent)}
.hint{font-size:12px;color:var(--muted);margin-top:6px}.empty{display:grid;place-items:center;height:200px;color:var(--muted);border:1px dashed var(--line);border-radius:12px;text-align:center;padding:16px}
footer{max-width:1240px;margin:0 auto;padding:0 24px 40px;color:var(--muted);font-size:12.5px}
@media (max-width:900px){main{grid-template-columns:1fr}nav{flex-direction:row;overflow-x:auto}nav button{min-width:200px}.grid{grid-template-columns:1fr}.views.two{grid-template-columns:1fr}.viewer{height:340px}}
</style></head><body>
<header>__BACK__<h1>What each tool does — on real proteins</h1>
<p class="lede">The YAUVI Structural Workbench evaluates structures you bring — from the PDB or AlphaFold. It does not predict folds. Explore public examples and their evidence; cross-species comparison includes two research-backed case studies in two fold families.</p>
<span class="note">Pre-public build · results from qualification panel v2 (collection 2.11) · drag to rotate, scroll to zoom</span></header>
<div class="orientation"><p><strong>Your first visit</strong>Choose a question → explore the structure → read what the evidence supports.</p><details><summary>New to protein structure? Start with these words</summary><dl><dt>Structure</dt><dd>A three-dimensional arrangement of a protein’s atoms.</dd><dt>Residue</dt><dd>One amino acid: a building block in the protein chain.</dd><dt>Å (ångström)</dt><dd>A very small distance: one ten-billionth of a metre.</dd><dt>RMSD</dt><dd>An average distance between corresponding atoms after two structures are aligned. Smaller means closer in that comparison.</dd><dt>Evidence gap</dt><dd>Information we do not have. It is not a negative biological result.</dd><dt>Model</dt><dd>A representation of structure. It may be experimentally determined or predicted; each example says which.</dd></dl></details></div>
<main><nav role="tablist" aria-label="Choose a scientific question">__NAV__</nav><div>__PANELS__</div></main>
<footer>Structures are public PDB or AlphaFold DB entries acquired for the qualification panel. Color keys distinguish measured annotations from protein or chain identity. SF-CSA values are frozen comparison records, with research evidence cited separately. Generated by <b>tools/build_3d_showcase.py</b>.<br>3D rendering: 3Dmol.js (BSD-3-Clause). __NOTICE__</footer>
<script>__3DMOL__</script>
<script id="data" type="application/json">__DATA__</script>
<script>__APPJS__</script></body></html>"""

APP_JS = r"""const DATA=JSON.parse(document.getElementById('data').textContent);const made={};
const bg=()=>getComputedStyle(document.documentElement).getPropertyValue('--view').trim()||'#ffffff';
function build(p){if(made[p.id])return;made[p.id]=[];
 p.viewers.forEach((v,i)=>{const el=document.getElementById(p.id+'-v'+i);const vw=$3Dmol.createViewer(el,{backgroundColor:bg(),antialias:true});
  vw.addModel(v.structure,v.fmt);vw.setStyle({},{});
  const col=a=>v.cmap[a.chain+':'+a.resi]||(v.by_chain&&v.by_chain[a.chain])||v.uniform||'#c8c8c8';
  vw.setStyle({hetflag:false},{cartoon:{colorfunc:col,thickness:0.4}});
  if(v.hetero)vw.setStyle({hetflag:true,resn:['HEM']},{stick:{colorscheme:'greenCarbon',radius:0.18}});
  (v.highlights||[]).forEach(h=>{vw.addStyle({chain:h.chain,resi:h.resi,hetflag:false},{stick:{color:h.color,radius:v.focus?0.4:0.28}});
   if(v.focus)vw.addStyle({chain:h.chain,resi:h.resi,hetflag:false,atom:'CA'},{sphere:{color:h.color,radius:0.9}});
   if(h.label&&h.at)vw.addLabel(h.label,{position:{x:h.at[0],y:h.at[1],z:h.at[2]},fontSize:13,fontColor:'#111',backgroundColor:h.color,backgroundOpacity:0.9,borderRadius:6,inFront:true,alignment:'bottomCenter'});});
  if(v.first_chain_only){const ch=(vw.selectedAtoms({hetflag:false})[0]||{}).chain;vw.setStyle({},{});
   vw.setStyle({chain:ch,hetflag:false},{cartoon:{colorfunc:col,thickness:0.4}});v._zoom={chain:ch,hetflag:false};}
  if(v.membrane){const m=v.membrane;
   vw.addBox({center:{x:m.cx,y:m.cy,z:0},dimensions:{w:m.span,h:m.span,d:2*m.half},color:'#E9C46A',opacity:0.12});
   [m.half,-m.half].forEach(z=>vw.addBox({center:{x:m.cx,y:m.cy,z:z},dimensions:{w:m.span,h:m.span,d:0.6},color:'#E9C46A',opacity:0.55}));}
  vw.zoomTo(v._zoom||{hetflag:false});
  if(v.zoom)vw.zoom(v.zoom);
  if(v.membrane)vw.rotate(-90,'x');
  if(v.focus){vw.zoomTo({or:v.focus.map(f=>({chain:f.chain,resi:f.resi}))});vw.zoom(0.55);}
  vw.render();made[p.id].push(vw);});if(p.motion)buildStateMotion(p);}
function show(id){document.querySelectorAll('nav button').forEach(b=>{b.setAttribute('aria-selected',b.dataset.id===id);b.tabIndex=b.dataset.id===id?0:-1;});
 if(id!=='state')stopStateMotion();
 document.querySelectorAll('section.panel').forEach(s=>s.classList.toggle('on',s.id==='p-'+id));
 const p=DATA.find(d=>d.id===id);build(p);(made[id]||[]).forEach(v=>{v.resize();v.render();});try{history.replaceState(null,'','#'+id)}catch(e){}}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.id)));
document.querySelector('nav').addEventListener('keydown',e=>{const tabs=[...document.querySelectorAll('nav button')];let i=tabs.indexOf(document.activeElement);if(i<0)return;if(e.key==='ArrowRight'||e.key==='ArrowDown')i=(i+1)%tabs.length;else if(e.key==='ArrowLeft'||e.key==='ArrowUp')i=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=tabs.length-1;else return;e.preventDefault();tabs[i].focus();show(tabs[i].dataset.id);});
window.addEventListener('hashchange',()=>{const h=location.hash.slice(1);if(DATA.some(d=>d.id===h))show(h);});
show((location.hash||'').slice(1)&&DATA.some(d=>d.id===location.hash.slice(1))?location.hash.slice(1):DATA[0].id);
"""

PAGE = PAGE.replace("</style>", (ROOT / "tools/showcase_ui.css").read_text() + "\n</style>")

APP_JS = (ROOT / "tools/showcase_state_motion.js").read_text() + "\n" + APP_JS


HOWTO = ("Generated from the qualification executor, so this is what actually ran. Run from "
         "evidence/benchmarks/qualification-v2/ after acquire_sources.py, or swap in your own files. "
         "Where two lines appear, structqc runs first and the analysis reads its evidence. "
         "Exit 0 = complete; 1 = ran, with some evidence unresolved (reported, not hidden); 2 = stopped.")


def render(panels: list[dict], workbench: bool = False, used: dict[str, str] | None = None) -> str:
    """`used` maps a panel id to extra HTML for 'How we used it'; public builds pass none."""
    nav, secs = [], []
    for p in panels:
        e = html.escape
        nav.append(f'<button role="tab" data-id="{p["id"]}"><div class="t">{e(p["title"])}</div>'
                   f'<div class="q">{e(p["question"])}</div></button>')
        if p["viewers"]:
            two = " two" if len(p["viewers"]) > 1 else ""
            views = "".join(
                f'<div class="vwrap">{f"<div class=cap>{e(v["label"])}</div>" if v["label"] else ""}'
                f'<div class="viewer" id="{p["id"]}-v{i}"></div></div>' for i, v in enumerate(p["viewers"]))
            views = f'<div class="views{two}">{views}</div>'
        else:
            views = '<div class="empty">A search across whole proteomes returns a table of matches,<br>not a single structure, so there is nothing to render in 3D.</div>'
        badge = ('<span class="badge ok">this case passed its qualification gate</span>' if p["passed"]
                 else '<span class="badge">gate result not recorded</span>')
        if p.get("badge_text"):
            badge = f'<span class="badge">{e(p["badge_text"])}</span>'
        link = f' · <a href="{e(p["link"])}" target="_blank" rel="noopener">{e(p["entry"])}</a>' if p["link"] else f' · {e(p["entry"])}'
        legend = "".join(f'<span><span class="sw" style="background:{c}"></span>{e(l)}</span>' for c, l in p["legend"])
        view_note = f'<p class="hint">{e(p["view_note"])}</p>' if p.get("view_note") else ""
        secs.append(
            f'<section class="panel" id="p-{p["id"]}" role="tabpanel"><p class="q2">{e(p["question"])}</p>'
            f'<p class="who">{e(p["protein"])}{link}</p>'
            f'{view_note}{state_motion_html(p)}<div class="grid"><div>{views}'
            f'{f"<h3>Color key</h3><div class=legend>{legend}</div>" if legend else ""}'
            f'<h3>How it gets this</h3><ol class="steps">{"".join(f"<li>{e(x)}</li>" for x in HOW[p["id"]]["how"])}</ol>'
            f'{sfcsa_research(p)}{(used or {}).get(p["id"], "")}</div><div>'
            f'<h3>What this tells you</h3><ul>{"".join(f"<li>{e(x)}</li>" for x in HOW[p["id"]]["gives"])}</ul>'
            f'<h3>What <b>{e(p["tool"])}</b> reported here</h3><ul>{"".join(f"<li>{e(x)}</li>" for x in p["reported"])}</ul>'
            f'<h3>Qualification</h3>{badge}<p class="hint">{e(p["scope"])}</p>'
            f'<h3>What it does not claim</h3><p class="hint" style="margin-top:0">{e(p["limit"])}</p>'
            f'<details class="advanced"><summary>Technical details: reproduce this result</summary><code>{e(chr(10).join(p["commands"]))}</code>'
            f'<p class="hint">{e(p.get("command_note", HOWTO))}</p></details></div></div></section>')
    data = json.dumps([{k: p[k] for k in ("id", "viewers", "motion") if k in p} for p in panels]).replace("</", "<\\/")
    notice = ('3Dmol.js incorporates code from GLmol, Three.js and jQuery; redistributed under its '
              'BSD-3-Clause license, whose full text is embedded in this page\'s source.')
    license = (VENDOR / "3DMOL-LICENSE.txt").read_text().replace("--", "- -")
    page = PAGE.replace("__NAV__", "".join(nav)).replace("__PANELS__", "".join(secs)).replace("__DATA__", data)
    if workbench:
        # Served by the workbench under a CSP that forbids inline script: the viewer and
        # this page's code load as files; the JSON block above is data, not script.
        return (page.replace("<script>__3DMOL__</script>", '<script src="/vendor/3Dmol-min.js"></script>')
                .replace("<script>__APPJS__</script>", '<script src="/showcase/showcase.js"></script>')
                .replace("__BACK__", '<p class="note" style="margin:0 0 12px"><a href="/">&larr; Back to your workbench</a></p>')
                .replace("__NOTICE__", '<a href="/vendor/3DMOL-LICENSE.txt">License</a>.'))
    return (page.replace("__BACK__", "").replace("__APPJS__", "\n" + APP_JS).replace("__NOTICE__", notice)
            .replace("__3DMOL__", (VENDOR / "3Dmol-min.js").read_text().replace("</script", "<\\/script"))
            .replace("</body>", f"<!--\n{license}\n--></body>"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(ROOT / "build" / "showcase-3d" / "index.html"))
    parser.add_argument("--workbench", action="store_true",
                        help="also write a CSP-safe copy to <out dir>/workbench/ for YAUVI_SHOWCASE_DIR")
    args = parser.parse_args()
    panels = [structqc(), membrane(), state(), site(), assembly(), sfcsa()]
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(panels))
    motion = next(p["motion"] for p in panels if "motion" in p)
    (out.parent / "ABL-endpoint-geometry.json").write_text(json.dumps(motion, indent=2) + "\n")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB, {len(panels)} panels)")
    if args.workbench:
        wb = out.parent / "workbench"
        wb.mkdir(exist_ok=True)
        (wb / "index.html").write_text(render(panels, workbench=True))
        (wb / "showcase.js").write_text(APP_JS)
        print(f"wrote {wb}/ -- launch with YAUVI_SHOWCASE_DIR={wb}")
    for p in panels:
        print(f"  {p['id']:9} passed={p['passed']}  viewers={len(p['viewers'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
