'use strict';
const $=id=>document.getElementById(id),palette=['#368375','#537cb1','#a87742','#995d93','#6c8c39','#b96858','#447c87','#7971a4'];
let current=null,view=null,viewer=null,model=null,version=0,selected=null,abort=null;
const element=(tag,text,cls)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;};
const endpoint=(...parts)=>'/api/biological-cases/'+parts.map(encodeURIComponent).join('/');
async function get(url,signal){const response=await fetch(url,{signal});const body=await response.json();if(!response.ok)throw Error(body.error||'Unable to load this case');return body;}
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';}
function options(id,items,placeholder){const select=$(id);select.replaceChildren(new Option(placeholder,''),...items.map(x=>new Option(x.label,x.id)));select.disabled=!items.length;if(items.length===1)select.value=items[0].id;}
function clearView(){version++;if(abort)abort.abort();abort=null;view=null;selected=null;if(viewer)viewer.clear();$('chain').replaceChildren();$('residue').replaceChildren();$('chain').disabled=$('residue').disabled=$('reset').disabled=$('bilayer').disabled=true;$('bilayer').checked=false;$('sequence').replaceChildren();$('annotations').replaceChildren();$('context').replaceChildren();$('measurements').textContent='No view selected.';$('residue-detail').textContent='Open a view, then select a sequence position or a backbone atom.';$('view-context').textContent='No coordinate view selected.';}
function sourceLink(id,label){const a=element('a',label||'Open source record ↗');a.href=endpoint(current.id,'sources',id);a.target='_blank';a.rel='noopener';return a;}
function assertionCard(a){const card=element('div',undefined,'record');card.append(element('strong',a.property.replaceAll('_',' ')),element('span',a.state,'tag'),element('span',a.basis,'tag'));const value=a.value==null?'Unknown':typeof a.value==='object'?JSON.stringify(a.value):String(a.value);card.append(element('p',value),element('p',a.interpretation_limit,'muted'),sourceLink(a.source_id));return card;}
function renderSources(){const box=$('sources');box.replaceChildren();for(const s of current.sources){const row=element('div',undefined,'record');row.append(sourceLink(s.id,s.label),element('pre','SHA-256 '+s.sha256));if(s.url){const a=element('a','Provider citation ↗');a.href=s.url;a.target='_blank';a.rel='noopener';row.append(a);}box.append(row);}}
function ready(){const ok=current&&$('structure').value&&$('model').value&&$('assembly').value;$('load').disabled=!ok;}
function structureChanged(){clearView();const s=current?.structures.find(x=>x.id===$('structure').value);options('model',(s?.models||[]).map(id=>({id,label:'Model '+id})),'Choose a model');options('assembly',s?.assemblies||[],'Choose an assembly');ready();}
async function chooseCase(){clearView();const generation=version;current=null;$('case-info').hidden=true;$('sources').replaceChildren();options('structure',[],'Choose a structure');options('model',[],'Choose a model');options('assembly',[],'Choose an assembly');ready();if(!$('case').value)return;abort=new AbortController();try{const data=await get(endpoint($('case').value),abort.signal);if(generation!==version)return;current=data;$('case-info').hidden=false;$('title').textContent=data.title;$('identity').textContent=data.protein.accession+' · '+data.protein.organism+' · '+data.protein.sequence.length+' residues';$('limits').textContent=data.limitations.join(' ');options('structure',data.structures.map(s=>({id:s.id,label:s.entry_id})),'Choose a structure');renderSources();structureChanged();notice('Choose the assembly you want to inspect.');}catch(e){if(e.name!=='AbortError'&&generation===version)notice(e.message,true);}}
function selectedChain(){return view?.chains.find(c=>c.id===$('chain').value);}
function matchesView(a){return !a.scope.structure_id||(a.scope.structure_id===view.structure_id&&a.scope.assembly_id===view.assembly_id&&a.scope.model_id===view.model_id);}
function annotations(position){$('annotations').replaceChildren();const records=current.assertions.filter(a=>a.scope.start!==undefined&&position!==null&&position>=a.scope.start&&position<=a.scope.end&&matchesView(a));if(!records.length)$('annotations').textContent='No mapped annotation for this position in the selected view.';else records.forEach(a=>$('annotations').append(assertionCard(a)));}
function selectResidue(residue,position=null,focus=false){selected=residue;const p=position??residue?.sequence_position??null;for(const b of $('sequence').children){const on=Number(b.dataset.position)===p;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on));if(on&&focus)b.focus();}$('residue').value=residue?.id||'';const box=$('residue-detail');box.replaceChildren(element('strong',p?'Sequence position '+p+' · '+current.protein.sequence[p-1]:'Unmapped coordinate residue'));if(residue){box.append(element('p','Chain '+selectedChain().label),element('p','Deposited residue '+(residue.auth_seq_id||'unassigned')+residue.insertion_code+' · '+residue.comp_id+' · label '+(residue.label_seq_id??'none')),element('p',residue.observed?'Coordinates present · '+residue.mapping_state:'Coordinates missing for this residue.'));if(residue.alternate_locations.length)box.append(element('p','Alternative conformers: '+residue.alternate_locations.join(', ')+'; displayed '+residue.selected_altloc));}else box.append(element('p','This reference position has no mapped coordinates in the selected chain.'));annotations(p);draw();}
function renderSequence(){const chain=selectedChain();$('sequence').replaceChildren();$('residue').replaceChildren(new Option('Choose a coordinate residue',''),...(chain?.residues||[]).map(r=>new Option((r.sequence_position?'Sequence '+r.sequence_position+' · ':'')+r.comp_id+' '+r.auth_seq_id+r.insertion_code+(r.observed?'':' · missing'),r.id)));$('residue').disabled=!chain;const map=new Map((chain?.residues||[]).filter(r=>r.sequence_position).map(r=>[r.sequence_position,r]));[...current.protein.sequence].forEach((aa,i)=>{const pos=i+1,r=map.get(pos),b=element('button',aa,r?.observed?'':'missing');b.dataset.position=pos;b.title='Position '+pos+' · '+aa+(r?.observed?'':' · no coordinates');b.setAttribute('aria-label',b.title);b.setAttribute('aria-pressed','false');b.onclick=()=>selectResidue(r,pos);b.onkeydown=e=>{const delta={ArrowRight:1,ArrowLeft:-1,ArrowDown:10,ArrowUp:-10}[e.key];if(delta){e.preventDefault();const next=Math.max(1,Math.min(current.protein.sequence.length,pos+delta));selectResidue(map.get(next),next,true);}};$('sequence').append(b);});selected=null;$('residue-detail').textContent='Select a sequence position or click a backbone atom.';$('annotations').replaceChildren();draw();}
function membrane(){if(!view?.membrane||!$('bilayer').checked)return;const m=view.membrane,n=m.normal,c=m.center;const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];let u=cross(n,Math.abs(n[0])<.8?[1,0,0]:[0,1,0]);const len=Math.hypot(...u);u=u.map(x=>x/len);const v=cross(n,u),extent=50;for(const sign of [-1,1]){const vertices=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([a,b])=>({x:c[0]+sign*m.half_thickness*n[0]+extent*(a*u[0]+b*v[0]),y:c[1]+sign*m.half_thickness*n[1]+extent*(a*u[1]+b*v[1]),z:c[2]+sign*m.half_thickness*n[2]+extent*(a*u[2]+b*v[2])}));viewer.addCustom({vertexArr:vertices,faceArr:[0,1,2,0,2,3],normalArr:vertices.map(()=>({x:n[0],y:n[1],z:n[2]})),color:'#baa0d0',alpha:.22,doubleSided:true});}}
function draw(){if(!viewer||!view)return;viewer.removeAllShapes();viewer.removeAllLabels();viewer.setStyle({},{sphere:{scale:.09,color:'#c4cdc8'}});view.chains.forEach((chain,index)=>{const color=palette[index%palette.length];viewer.setStyle({chain:chain.id,atom:'CA'},{sphere:{radius:.45,color}});let previous=null;for(const r of chain.residues){const a=r.atom_indices.map(i=>view.atoms[i]).find(a=>a.atom==='CA');if(a&&previous&&r.label_seq_id===previous.residue.label_seq_id+1&&Math.hypot(a.x-previous.atom.x,a.y-previous.atom.y,a.z-previous.atom.z)<4.6)viewer.addCylinder({start:previous.atom,end:a,radius:.20,color,fromCap:1,toCap:1});previous=a?{atom:a,residue:r}:null;}});if(selected?.atom_indices.length)viewer.addStyle({serial:selected.atom_indices},{sphere:{scale:.5,color:'#da922e'}});membrane();viewer.render();}
async function openView(){const sid=$('structure').value,mid=$('model').value,aid=$('assembly').value;if(!current||!sid||!mid||!aid)return;clearView();const generation=version;abort=new AbortController();$('load').disabled=true;notice('Checking identities and assembling this view…');try{const data=await get(endpoint(current.id,'view',sid,mid,aid),abort.signal);if(generation!==version)return;view=data;if(!viewer)viewer=$3Dmol.createViewer($('viewer'),{backgroundColor:'#f7faf8'});viewer.clear();model=viewer.addModel();model.addAtoms(data.atoms);viewer.setClickable({atom:'CA'},true,atom=>{const id=atom.properties?.residue_id;const chain=view.chains.find(c=>c.residues.some(r=>r.id===id));if(!chain)return;if($('chain').value!==chain.id){$('chain').value=chain.id;renderSequence();}selectResidue(chain.residues.find(r=>r.id===id));});options('chain',data.chains.filter(c=>c.residues.some(r=>r.sequence_position)).map(c=>({id:c.id,label:c.label})),'Choose a chain copy');if(!$('chain').value&&$('chain').options.length>1)$('chain').selectedIndex=1;$('chain').disabled=false;$('reset').disabled=false;$('bilayer').disabled=!data.membrane;$('context').replaceChildren(...current.assertions.filter(a=>a.scope.start===undefined&&matchesView(a)).map(assertionCard));$('measurements').replaceChildren();for(const e of data.evidence){const row=element('div',undefined,'record');row.append(element('strong',e.engine.replaceAll('_',' ')),element('span',e.state,'tag'),element('pre',JSON.stringify(e.summary,null,2)),element('p',e.interpretation_limit,'muted'),sourceLink(e.source_id));$('measurements').append(row);}if(!data.evidence.length)$('measurements').textContent='No engine output is bound to this exact model and assembly. Other views may have separate evidence.';renderSequence();viewer.zoomTo();viewer.resize();viewer.render();$('view-context').textContent=data.atoms.length.toLocaleString()+' atoms · '+data.chains.filter(c=>c.residues.some(r=>r.sequence_position)).length+' protein copies · backbone trace. '+(data.membrane?'Modeled membrane available; sidedness unknown.':'No membrane placement bound to this view.');notice(data.warnings.join(' ')||'View ready. Select a residue to trace its evidence.');}catch(e){if(e.name!=='AbortError'&&generation===version){clearView();notice(e.message,true);}}finally{ready();}}
$('case').onchange=chooseCase;$('structure').onchange=structureChanged;for(const id of ['model','assembly'])$(id).onchange=()=>{clearView();ready();};$('load').onclick=openView;$('chain').onchange=renderSequence;$('residue').onchange=()=>selectResidue(selectedChain()?.residues.find(r=>r.id===$('residue').value));$('reset').onclick=()=>{viewer.zoomTo();viewer.render();};$('bilayer').onchange=draw;window.addEventListener('resize',()=>{if(viewer){viewer.resize();viewer.render();}});
get('/api/biological-cases').then(cases=>{options('case',cases.filter(c=>c.state==='ready').map(c=>({id:c.id,label:c.title})),'Choose a case');$('case').value='';notice(cases.some(c=>c.state==='ready')?'Choose a local biological case.':'No verified cases found. Build or register a local biological case first.');}).catch(e=>notice(e.message,true));
