'use strict';
const $ = id => document.getElementById(id);
const el = (tag,text,cls) => {const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const names={structure_qc:'Structure quality',membrane_orientation:'Membrane orientation',conformational_state:'Conformational state',functional_site_state:'Functional sites',assembly_interface:'Assembly & interfaces',sf_csa:'Sequence & structural specificity'};
const states={draft:'Not run',completed:'Execution complete',scientifically_incomplete:'Finished · evidence incomplete',failed:'Execution failed',blocked:'Needs attention',queued:'Waiting',running:'Running',cancelled:'Cancelled',interrupted:'Interrupted'};
const friendly=v=>String(v??'').replaceAll('_',' ');
let token='',definitions=[],sourceRows=[],caseRows=[],jobs=[],selected='structure_qc',current=null,snapshot=null,canFetch=false;
let viewer=null,model=null,loadedCoordinate='',panel='setup',selectionVersion=0,historyVersion=0,dirty=false,busy=false,polling=false;
const seenJobs=new Map(), pendingResults=new Set();
function notice(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':'';const dialog=document.querySelector('dialog[open]');if(dialog&&error){let n=dialog.querySelector('.dialog-notice');if(!n){n=el('p',undefined,'dialog-notice boundary');n.setAttribute('role','alert');dialog.append(n);}n.textContent=message;}}
async function api(path,data,method='POST'){
 const raw=data instanceof ArrayBuffer;
 const response=await fetch(path,{method:data===undefined?'GET':method,headers:data===undefined?{}:{'Content-Type':raw?'application/octet-stream':'application/json','X-Yauvi-Token':token},body:data===undefined?undefined:raw?data:JSON.stringify(data)});
 const result=await response.json();if(!response.ok)throw Error(result.error||'The local request failed.');return result;
}
const guard=fn=>async event=>{try{await fn(event);}catch(error){notice(error.message,true);}};
async function exclusive(fn){if(busy)throw Error('Wait for the current update to finish.');busy=true;updateActions();try{return await fn();}finally{busy=false;updateActions();}}
function setPanel(name){panel=name;for(const b of document.querySelectorAll('[data-panel]')){if(b.dataset.panel===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');$('panel-'+b.dataset.panel).hidden=b.dataset.panel!==name;}if(name==='results'&&viewer){viewer.resize();viewer.render();}}
for(const b of document.querySelectorAll('[data-panel]'))b.onclick=()=>setPanel(b.dataset.panel);
function showNew(){if(busy)return;$('new-dialog').showModal();choose(selected);}
$('new').onclick=showNew;$('start').onclick=showNew;$('close-new').onclick=()=>$('new-dialog').close();
for(const id of ['try-example','welcome-example'])$(id).onclick=()=>$('example-dialog').showModal();
$('close-example').onclick=()=>$('example-dialog').close();$('close-activity').onclick=()=>$('activity-dialog').close();
$('show-activity').onclick=()=>{$('activity-dialog').showModal();renderJobs();};
function choose(type){selected=type;document.querySelectorAll('.workflow').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.type===type)));const d=definitions.find(d=>d.analysis_type===type);if(!d)return;$('workflow-detail').replaceChildren(el('strong',d.title),el('p',d.use_when),el('p',d.claim_ceiling,'muted'));$('question').placeholder=d.question||'What can this structure support?';}
function renderCases(){
 const q=$('search').value.trim().toLowerCase();const rows=caseRows.filter(r=>[r.subject_id,r.question,r.analysis_id,names[r.analysis_type]].join(' ').toLowerCase().includes(q));
 $('cases').replaceChildren(...rows.map(r=>{const b=el('button',undefined,'case');b.setAttribute('aria-current',String(r.analysis_id===current));b.title=r.question+' · '+r.analysis_id;b.append(el('strong',r.subject_id||r.question),el('span',names[r.analysis_type]),el('span',(states[r.state]||friendly(r.state))+' · '+r.analysis_id.slice(-6)));b.onclick=guard(()=>openCase(r.analysis_id));return b;}));
 if(!rows.length)$('cases').append(el('p',q?'No matching analyses.':'Your analyses will appear here.','muted'));
}
$('search').oninput=renderCases;
async function refreshCases(){caseRows=await api('/api/analyses');renderCases();}
function resetViewer(){if(viewer)viewer.clear();viewer=null;model=null;loadedCoordinate='';$('viewer').replaceChildren(el('p','Load an attached structure to explore it here.','viewer-placeholder'));$('chain').replaceChildren(new Option('All chains','*'));$('residue').replaceChildren(new Option('Select a residue',''));for(const id of ['chain','residue','representation','ligands','reset-view'])$(id).disabled=true;$('viewer-context').textContent='Coordinates alone do not validate identity, function or activity.';}
async function openCase(id,{internal=false}={}){
 if(!internal&&(busy||dirty))throw Error(dirty?'Save your parameter changes before opening another analysis.':'Please let the current update finish first.');
 const version=++selectionVersion;const value=await api('/api/analyses/'+encodeURIComponent(id));if(version!==selectionVersion)return;
 if(current!==id){resetViewer();$('experimental').checked=false;setPanel('setup');}
 current=id;snapshot=value;pendingResults.delete(id);dirty=false;historyVersion++;render();renderCases();renderJobs();
}
function renderPreflight(value){
 const box=$('preflight');box.replaceChildren();if(!value)return;
 if(value.revision_sha256!==snapshot.analysis.revision_sha256){box.append(el('p','These checks belong to an earlier revision. Check readiness again before a new run.','muted'));return;}
 box.append(el('h3',value.valid?'Ready to execute':'Before you run'),el('p',value.valid?'The software can run. Missing optional evidence may still limit the result.':'Resolve these items, then check readiness again.','muted'));
 const list=checks=>{const ul=el('ul',undefined,'check-list');for(const c of checks){const li=el('li',undefined,c.ok?'passed':'needs');li.append(el('strong',(c.ok?'✓ ':'• ')+friendly(c.name)),el('span',c.detail));ul.append(li);}return ul;};
 box.append(list((value.checks||[]).filter(c=>!c.ok)));const passed=(value.checks||[]).filter(c=>c.ok);
 if(passed.length){const d=el('details');d.append(el('summary',passed.length+' checks passed'),list(passed));box.append(d);}
}
function inputCard(role){
 const attached=snapshot.analysis.inputs.filter(i=>i.role===role.role),box=el('article',undefined,'input-row'),head=el('div',undefined,'input-head');
 head.append(el('strong',role.label||friendly(role.role)),el('span',attached.length?attached.length+' attached':role.required?'Required':'Optional','badge'));box.append(head,el('p',role.description));
 const why=el('details');why.append(el('summary','Why this matters'),el('p',role.why_needed));if(role.absence_effect)why.append(el('p',role.absence_effect));box.append(why);
 for(const i of attached){const item=el('div',undefined,'attached'),link=el('a',i.file_name);link.href=`/api/analyses/${current}/inputs/${i.sha256}`;link.download=i.file_name;item.append(link,el('span',i.bytes.toLocaleString()+' bytes · checksum verified on import'));const d=el('details');d.append(el('summary','File identity'),el('code',i.sha256));item.append(d);box.append(item);}
 if(role.multiple||!attached.length){const label=el('label','Add '+(role.label||friendly(role.role))),input=el('input');input.type='file';input.accept=role.accepted_extensions.join(',');input.onchange=guard(async()=>{if(input.files[0])await exclusive(()=>upload(role.role,input.files[0]));});label.append(input);box.append(label);if(role.minimum_files>1)box.append(el('p',`At least ${role.minimum_files} files are required. Add them one at a time.`,'muted'));}
 if(role.template_id){const link=el('a','Download a format template');link.href='/api/templates/'+encodeURIComponent(role.template_id);box.append(link);}return box;
}
function render(){
 const {analysis:a,definition:d}=snapshot;$('analysis').hidden=false;$('empty').hidden=true;$('analysis-type').textContent=names[a.analysis_type]||d.title;$('analysis-subject').textContent=a.subject_id;$('analysis-question').textContent=a.question;$('status').textContent=states[a.state]||friendly(a.state);
 $('qualification').replaceChildren(el('strong',a.analysis_type==='membrane_orientation'?'Experimental':'Scientific qualification incomplete'),el('span',' · '+(a.analysis_type==='sf_csa'?'Qualification reference universe unresolved.':'Execution status and biological validity are separate.')));
 $('experimental-label').hidden=a.analysis_type!=='membrane_orientation';
 const required=d.inputs.filter(r=>r.required),optional=d.inputs.filter(r=>!r.required);
 $('inputs').replaceChildren(...required.map(inputCard));$('optional-files').replaceChildren(...optional.map(inputCard));$('optional-inputs').hidden=!optional.length;
 $('input-count').textContent=`${required.filter(r=>a.inputs.filter(i=>i.role===r.role).length>=(r.minimum_files||1)).length} of ${required.length} required roles attached`;
 $('optional-count').textContent=a.inputs.filter(i=>optional.some(r=>r.role===i.role)).length+' files attached';
 const form=$('parameters');form.replaceChildren();$('parameter-details').hidden=!(d.parameters||[]).length;
 for(const p of d.parameters||[]){const label=el('label',friendly(p.name)),input=el(p.type==='select'?'select':'input');if(p.type==='select')for(const choice of p.choices)input.append(new Option(friendly(choice),choice));else if(['integer','number'].includes(p.type)){input.type='number';input.min=p.name==='stride'?'1':'0';input.step=p.type==='integer'?'1':'any';}input.name=p.name;input.value=a.parameters[p.name]??p.default??'';input.dataset.kind=p.type||'';input.oninput=()=>{dirty=true;updateActions();};label.append(input);if(p.description)label.append(el('span',p.description,'parameter-hint'));form.append(label);}
 if(d.parameters?.length)form.append(el('button','Save parameters'));
 renderPreflight(snapshot.preflight);renderSources();renderResults();renderTrace();updateActions();
 const coords=a.inputs.filter(i=>/\.(pdb|cif|mmcif)$/i.test(i.file_name)),previous=$('coordinate').value;
 $('coordinate').replaceChildren(...coords.map(i=>new Option(friendly(i.role)+' · '+i.file_name,i.sha256)));if(coords.some(i=>i.sha256===previous))$('coordinate').value=previous;
 if(!coords.length)$('coordinate').append(new Option('No coordinates attached',''));$('view').disabled=!coords.length;$('coordinate').disabled=!coords.length;
}
function updateActions(){
 if(!snapshot)return;const active=jobs.some(j=>j.analysis_id===current&&['queued','running'].includes(j.state));const valid=snapshot.preflight?.valid&&snapshot.preflight.revision_sha256===snapshot.analysis.revision_sha256;const experimental=snapshot.analysis.analysis_type==='membrane_orientation';
 $('run').disabled=busy||dirty||active||!valid||(experimental&&!$('experimental').checked);$('validate').disabled=busy||dirty||active;$('run').textContent=active?'In progress':'Run analysis';$('parameter-note').textContent=dirty?'Unsaved changes':'';
 $('next-action').textContent=active?'An analysis is in progress':dirty?'Save your parameters':valid?'Ready for the next step':'Check your inputs';
 $('next-description').textContent=active?'Open Process to follow or cancel the run.':dirty?'Save this revision before checking or running it.':valid?(experimental&&!$('experimental').checked?'Acknowledge the experimental limits below to continue.':'Ready to execute. Interpretation still depends on the evidence.'):'Readiness checks include required files and installed tools.';
 $('running-dot').hidden=!active;const activeJob=jobs.find(j=>j.analysis_id===current&&['queued','running'].includes(j.state));$('status').textContent=activeJob?(states[activeJob.state]||friendly(activeJob.state)):(states[snapshot.analysis.state]||friendly(snapshot.analysis.state));
 for(const input of $('panel-setup').querySelectorAll('input[type=file],#parameters input,#parameters select,#parameters button'))input.disabled=busy||active;
}
async function upload(role,file){
 const id=current;if(!file.size||file.size>250*1024*1024)throw Error('Choose a non-empty file up to 250 MiB.');if(dirty)throw Error('Save parameter changes before adding a file.');notice('Checking '+file.name+'…');
 const data=await file.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),b=>b.toString(16).padStart(2,'0')).join('');
 const rec=await api(`/api/analyses/${id}/ingest`,{role,file_name:file.name,size:file.size,sha256:hash});let index=0;
 for(let offset=0;offset<data.byteLength;offset+=8*1024*1024){const chunk=data.slice(offset,offset+8*1024*1024);await api(`/api/ingests/${rec.upload_id}/${index++}`,chunk,'PUT');notice(`Importing ${file.name} · ${Math.round(100*(offset+chunk.byteLength)/data.byteLength)}% transferred`);}
 await api(`/api/ingests/${rec.upload_id}/finalize`,{});await openCase(id,{internal:true});notice('Imported and checksum verified: '+file.name);
}
$('example').onclick=guard(()=>exclusive(async()=>{if(dirty)throw Error('Save your parameter changes before loading an example.');$('example').disabled=true;try{const r=await api('/api/examples/structure-qc',{without_validation:$('example-missing').checked});$('example-dialog').close();await refreshCases();await openCase(r.analysis.analysis_id,{internal:true});notice('Example ready. Check readiness, then run to see measurements.');}finally{$('example').disabled=false;}}));
$('create').onsubmit=guard(e=>{e.preventDefault();return exclusive(async()=>{if(dirty)throw Error('Save parameter changes before creating another analysis.');const id='case-'+Date.now().toString(36)+'-'+crypto.randomUUID().slice(0,6);await api('/api/analyses',{analysis_id:id,analysis_type:selected,question:$('question').value,subject_id:$('subject').value});$('new-dialog').close();await refreshCases();await openCase(id,{internal:true});notice('Analysis created. Start with the required evidence.');});});
$('parameters').onsubmit=guard(e=>{e.preventDefault();return exclusive(async()=>{const id=current,parameters={};for(const input of $('parameters').querySelectorAll('input,select'))if(input.value!=='')parameters[input.name]=['integer','number'].includes(input.dataset.kind)?Number(input.value):input.value;await api(`/api/analyses/${id}/parameters`,{parameters});dirty=false;await openCase(id,{internal:true});await refreshCases();notice('Parameters saved. Check readiness for this revision.');});});
$('experimental').onchange=updateActions;
$('validate').onclick=guard(()=>exclusive(async()=>{const id=current,result=await api(`/api/analyses/${id}/validate`,{});if(current===id){snapshot.preflight=result;renderPreflight(result);updateActions();}notice(result.valid?'Ready to execute. Scientific qualification remains a separate check.':'Some inputs or tools need attention. See the readiness checks.',!result.valid);}));
$('run').onclick=guard(()=>exclusive(async()=>{await api(`/api/analyses/${current}/run`,{experimental_acknowledged:$('experimental').checked});setPanel('process');notice('Run submitted. Follow its actual stages below.');await refreshJobs();}));
function jobCard(job,detailed=false){
 const row=caseRows.find(r=>r.analysis_id===job.analysis_id),box=el('article',undefined,detailed?'live-card':'job'),head=el('div',undefined,'live-title');
 head.append(el('h3',job.cancel_requested&&job.state==='running'?'Stopping safely':states[job.state]||friendly(job.state)));const clock=el('span','','elapsed');clock.dataset.start=job.started_at||job.created_at||'';clock.dataset.end=job.finished_at||'';head.append(clock);box.append(head,el('p',`${row?.subject_id||job.analysis_id} · ${job.analysis_id.slice(-6)}`,'muted'));
 if(job.queue_position)box.append(el('p',`Position ${job.queue_position} in the queue. One analysis runs at a time.`,'muted'));
 if(detailed&&job.events?.length){const timeline=el('ol',undefined,'timeline');for(const e of job.events){const item=el('li',e.message),time=el('time',new Date(e.at).toLocaleTimeString());time.dateTime=e.at;item.append(time);timeline.append(item);}box.append(timeline);}else if(detailed)box.append(el('p','This older job has no stage log. Its recorded outcome is preserved.','muted'));
 if(job.error)box.append(el('p',job.error,'boundary'));const actions=el('div',undefined,'actions');
 if(['queued','running'].includes(job.state)){const cancel=el('button',job.cancel_requested?'Cancellation requested':'Cancel run','secondary');cancel.disabled=!!job.cancel_requested;cancel.onclick=guard(async()=>{cancel.disabled=true;try{await api(`/api/jobs/${job.job_id}/cancel`,{});await refreshJobs();}catch(e){cancel.disabled=false;throw e;}});actions.append(cancel);}
 if(!detailed||job.run_id){const open=el('button',job.run_id?'Open recorded result':'Open analysis','quiet');open.onclick=guard(async()=>{$('activity-dialog').close();await openCase(job.analysis_id);if(job.run_id){await selectRun(job.run_id);setPanel('results');}else setPanel('process');});actions.append(open);}box.append(actions);return box;
}
function renderJobs(){const reverse=[...jobs].reverse(),mine=reverse.filter(j=>j.analysis_id===current);$('job-count').textContent=jobs.filter(j=>['queued','running'].includes(j.state)).length+' active';$('live-job').replaceChildren(mine.length?jobCard(mine[0],true):el('p','No job submitted yet. Check readiness in Inputs, then run.','empty-state'));for(const id of ['jobs','all-activity'])$(id).replaceChildren(...reverse.map(j=>jobCard(j)));if(!reverse.length)for(const id of ['jobs','all-activity'])$(id).append(el('p','No activity yet.','muted'));updateClocks();updateActions();}
function updateClocks(){for(const clock of document.querySelectorAll('.elapsed')){if(!clock.dataset.start){clock.textContent='Time not recorded';continue;}const seconds=Math.max(0,Math.floor(((clock.dataset.end?Date.parse(clock.dataset.end):Date.now())-Date.parse(clock.dataset.start))/1000));clock.textContent=`${Math.floor(seconds/60)}m ${String(seconds%60).padStart(2,'0')}s`;}}
async function refreshJobs(){
 if(polling)return;polling=true;
 try{const rows=await api('/api/jobs');let changed=false;for(const row of rows){const signature=JSON.stringify(row);if((seenJobs.has(row.job_id)?signature!==seenJobs.get(row.job_id):!!row.run_id)&&!['queued','running'].includes(row.state)){pendingResults.add(row.analysis_id);changed=true;}seenJobs.set(row.job_id,signature);}const rerender=JSON.stringify(rows)!==JSON.stringify(jobs);jobs=rows;$('connection').textContent='Live · connected';if(rerender)renderJobs();if(changed)await refreshCases();if(current&&pendingResults.has(current)&&!dirty&&!busy){pendingResults.delete(current);await openCase(current,{internal:true});notice('Run finished. Open Findings to inspect its outcome and limits.');}}
 catch(error){$('connection').textContent='Connection lost · retrying';throw error;}finally{polling=false;}
}
async function selectRun(runId){const id=current,version=++historyVersion,value=await api(`/api/analyses/${id}/runs/${runId}`);if(current!==id||version!==historyVersion)return;for(const key of ['run','report','run_inputs','available_artifacts','report_matches_case'])snapshot[key]=value[key];renderResults();renderTrace();}
$('history').onchange=guard(()=>selectRun($('history').value));$('trace-result').onclick=()=>setPanel('trace');
function renderResults(){
 const r=snapshot.report,box=$('findings');box.replaceChildren();$('result-context').textContent=snapshot.run?`${states[snapshot.run.status]||friendly(snapshot.run.status)} · ${snapshot.run.run_id}`:'No recorded run yet. Check readiness in Inputs to begin.';
 $('result-stale').hidden=!r||snapshot.report_matches_case;$('result-stale').textContent='This result uses an earlier input or parameter revision. Its evidence is preserved below. Check and run the current case to measure your changes.';
 if(!r){box.append(el('p',snapshot.run?.error||'No measurements yet. You can still explore attached coordinates below.','empty-state'));return;}
 if(r.status==='scientifically_incomplete')box.append(el('p','The calculations finished, but supporting evidence is incomplete. Review the gaps below before interpreting the measurements.','boundary'));
 const stepList=el('ul',undefined,'check-list');for(const step of r.steps||[]){const li=el('li');li.append(el('strong',friendly(step.module_id)+' — '+(step.exit_code===0?'finished':step.exit_code===1?'finished with incomplete scientific evidence':'execution failed')));stepList.append(li);}box.append(stepList);
 box.append(el('p',r.claim_ceiling,'boundary'));const metrics=el('div',undefined,'result-grid');
 // Project explicit engine fields; never infer a biological score.
 (r.documents||[]).forEach((item,index)=>{const c=item.document?.completeness;if(!c||typeof c!=='object')return;for(const [key,label] of [['coordinate_residues','Coordinate residues'],['mapped_residues','Mapped residues'],['reference_length','Reference length'],['coverage_fraction','Reference coverage']]){if(typeof c[key]!=='number')continue;const card=el('article',undefined,'metric');card.append(el('span',label),el('strong',key==='coverage_fraction'?(c[key]*100).toFixed(1)+'%':String(c[key])));const b=el('button','View source measurement ↗');b.onclick=()=>{const d=$('document-'+index);d.open=true;d.scrollIntoView({block:'center'});};card.append(b);metrics.append(card);}});
 if(r.analysis_type==='membrane_orientation'){
  const index=(r.documents||[]).findIndex(d=>d.path==='outputs/memorient/MEMBRANE_ORIENTATION.json');
  const summary=r.documents[index]?.document?.summary;
  if(summary)for(const [key,label,unit] of [['n_residues','Analyzed residues',''],['half_thickness','Modeled membrane half-thickness',' Å'],['n_embedded','Modeled embedded residues','']]){
   if(typeof summary[key]!=='number')continue;const card=el('article',undefined,'metric');card.append(el('span',label),el('strong',String(summary[key])+unit));
   const button=el('button','View source measurement ↗');button.onclick=()=>{const detail=$('document-'+index);detail.open=true;detail.scrollIntoView({block:'center'});};card.append(button);metrics.append(card);
  }
 }
 if(metrics.children.length)box.append(metrics);const gaps=r.missing_evidence||[];
 if(gaps.length){box.append(el('h3','Evidence gaps and warnings'));const ul=el('ul');gaps.forEach(g=>{
  const explanations={provenance:'Model provenance is undeclared. Attach a provenance record; a filename or AlphaFold header alone is only a hint.',reference_sequence:'No reference FASTA was supplied, so sequence identity and completeness have not been checked.',community_geometry_validation:'No geometry validation report was supplied. Coordinate quality remains unvalidated.',independent_second_machine_reproduction:'This result has not been independently reproduced on another machine.'};
  ul.append(el('li',explanations[g]||g));
 });box.append(ul);}else box.append(el('p','No missing-evidence entries were reported. Review method outputs for their specific scope.','muted'));
 if(['failed','cancelled','blocked','interrupted'].includes(r.status))box.append(el('p','This run did not complete successfully. Inspect the recorded outcome before reusing any partial outputs.','muted'));
 box.append(el('h3','Measurements and method outputs'),el('p','Open a source to inspect exact values. Tables show a preview; the full evidence bundle retains the original files.','muted'));
 (r.documents||[]).forEach((item,index)=>{const d=el('details');d.id='document-'+index;d.append(el('summary',item.path),el('pre',JSON.stringify(item.document,null,2)));box.append(d);});
 for(const table of r.tables||[]){const d=el('details');d.append(el('summary',table.path),el('p',`Showing ${Math.min(100,table.rows.length)} rows${table.truncated||table.rows.length>100?' · preview limited; download full evidence for the complete file':''}.`,'muted'));const wrap=el('div',undefined,'table-wrap'),t=el('table'),head=el('tr');for(const c of table.columns){const th=el('th',c);th.scope='col';head.append(th);}t.append(head);for(const row of table.rows.slice(0,100)){const tr=el('tr');for(const c of table.columns)tr.append(el('td',typeof row[c]==='object'?JSON.stringify(row[c]):String(row[c]??'')));t.append(tr);}wrap.append(t);d.append(wrap);box.append(d);}
}
function renderTrace(){
 const {analysis:a,run,report,run_inputs:inputs}=snapshot;$('history').replaceChildren(...[...(a.runs||[])].reverse().map(r=>new Option(`${r.run_id.slice(4,12)} · ${states[r.status]||friendly(r.status)}`,r.run_id)));if(run)$('history').value=run.run_id;if(!a.runs?.length)$('history').append(new Option('No recorded runs',''));$('history').disabled=!a.runs?.length;
 $('trace-chain').replaceChildren();const record=inputs||a;const step=(title,text)=>{const n=el('article',undefined,'trace-step');n.append(el('h3',title),el('p',text));$('trace-chain').append(n);return n;};
 const inputStep=step('1. Inputs',`${record.inputs.length} attached files · ${inputs?'the exact revision used by this run':'the current case; no run selected'}.`);
 for(const i of record.inputs){const d=el('details');d.append(el('summary',friendly(i.role)+' · '+i.file_name),el('code','SHA-256 '+i.sha256));inputStep.append(d);}
 const method=step('2. Method',run?(run.steps||[]).map(s=>`${s.module_id} (exit ${s.exit_code})`).join(' → ')||'No completed engine steps recorded.':'The selected workflow uses the same scientific engines as the CLI.');const d=el('details');d.append(el('summary','Parameters, software and runtime identities'),el('pre',JSON.stringify({parameters:record.parameters,software:run?.scientific_source_sha256,runtime:run?.runtime_versions},null,2)));method.append(d);
 step('3. Measurements',report?`${report.documents.length} method documents and ${report.tables.length} measurement tables. Open Findings to inspect them.`:'No report is available for this selection.');
 step('4. Interpretation',report?.claim_ceiling||snapshot.definition.claim_ceiling);step('5. Qualification & reproduction',`Scientific qualification: ${friendly(run?.scientific_qualification||'not independently qualified')}. Independent reproduction: ${friendly(run?.independent_reproduction||'not recorded')}.`);
 $('evidence').textContent=JSON.stringify({current_case:a,run_input_case:inputs,run,preflight:snapshot.preflight},null,2);
 const labels={'REPORT.html':['Readable report','Measurements and interpretation'],'REPORT_DATA.json':['Report data','Machine-readable measurements'],'RAW_EVIDENCE.zip':['Full evidence bundle','Original method outputs and provenance'],'CHECKSUMS.json':['File checksums','Verify the exact exported bytes'],'RUN_MANIFEST.json':['Reproduction manifest','Inputs, parameters and software identities']};$('downloads').replaceChildren();
 for(const name of snapshot.available_artifacts||[]){const link=el('a',labels[name][0]);link.href=`/api/analyses/${current}/artifacts/${run.run_id}/${name}`;link.download=name;link.append(el('span',labels[name][1]));$('downloads').append(link);}if(!$('downloads').children.length)$('downloads').append(el('p','Downloads appear when report files are available.','muted'));
}
function styleViewer(){if(!viewer||!model)return;const rep=$('representation').value;viewer.setStyle({},rep==='cartoon'?{cartoon:{color:'spectrum'}}:rep==='stick'?{stick:{colorscheme:'Jmol'}}:{sphere:{colorscheme:'Jmol',scale:.5}});viewer.setStyle({hetflag:true},$('ligands').checked?{stick:{colorscheme:'Jmol'}}:{});const chain=$('chain').value,residue=$('residue').value;if(chain!=='*'&&rep==='cartoon')viewer.setStyle({chain},{cartoon:{color:'#2670b5'}});if(residue){const selection={serial:JSON.parse(residue)};viewer.addStyle(selection,{stick:{color:'#d79635'},sphere:{scale:.3}});viewer.zoomTo(selection);}viewer.render();}
function updateResidues(){if(!model)return;const chain=$('chain').value,seen=new Map();for(const atom of model.selectedAtoms(chain==='*'?{}:{chain})){const key=JSON.stringify([atom.chain||'',atom.resi,atom.icode||'',atom.resn]);if(!seen.has(key))seen.set(key,{label:`${atom.chain||'(blank)'} · ${atom.resn} ${atom.resi}${atom.icode||''}`,serials:[]});seen.get(key).serials.push(atom.serial);}$('residue').replaceChildren(new Option('Select a residue',''),...Array.from(seen.values(),r=>new Option(r.label,JSON.stringify(r.serials))));}
$('view').onclick=guard(async()=>{const id=current,digest=$('coordinate').value,input=snapshot.analysis.inputs.find(i=>i.sha256===digest);if(!input)throw Error('Attach a coordinate file first.');$('view').disabled=true;try{const response=await fetch(`/api/analyses/${id}/inputs/${digest}`);if(!response.ok)throw Error('The coordinate file is unavailable.');const text=await response.text();if(current!==id||$('coordinate').value!==digest)return;if(viewer)viewer.clear();$('viewer').replaceChildren();viewer=$3Dmol.createViewer($('viewer'),{backgroundColor:'#fafbfd'});model=viewer.addModel(text,/\.pdb$/i.test(input.file_name)?'pdb':'cif');const atoms=model.selectedAtoms({});if(!atoms.length){resetViewer();throw Error('No displayable atoms were found. Check the coordinate format.');}loadedCoordinate=digest;if(atoms.length<50)$('representation').value='stick';const chains=[...new Set(atoms.map(a=>a.chain||''))].sort();$('chain').replaceChildren(new Option('All chains','*'),...chains.map(c=>new Option(c||'(blank)',c)));for(const name of ['chain','residue','representation','ligands','reset-view'])$(name).disabled=false;updateResidues();styleViewer();viewer.zoomTo();viewer.render();$('viewer-context').textContent=`${input.file_name} · ${atoms.length.toLocaleString()} displayed atoms · current case coordinates. Exact file identity is in Inputs.`;}finally{$('view').disabled=!$('coordinate').value;}});
$('coordinate').onchange=()=>{if($('coordinate').value!==loadedCoordinate)resetViewer();};$('reset-view').onclick=()=>{if(!viewer)return;$('chain').value='*';updateResidues();styleViewer();viewer.zoomTo();viewer.render();};$('chain').onchange=()=>{updateResidues();styleViewer();};$('residue').onchange=styleViewer;$('representation').onchange=styleViewer;$('ligands').onchange=styleViewer;
$('structure-details').ontoggle=()=>{if(viewer&&$('structure-details').open){viewer.resize();viewer.render();}};window.addEventListener('resize',()=>{if(viewer&&panel==='results'){viewer.resize();viewer.render();}});
function renderSources(){
 $('source-mode').textContent=canFetch?'Public retrieval is enabled. Only a selected reference is fetched when you press Retrieve.':'Public retrieval is off. Attach local files, or opt in later by starting the server with --allow-reference-fetch. No source is contacted automatically.';
 const boxes=[];for(const source of sourceRows){const relevant=source.artifacts.filter(a=>snapshot.definition.inputs.some(r=>r.accepted_artifact_types?.includes(a.artifact_type)));if(!relevant.length)continue;const box=el('div',undefined,'input-row');box.append(el('strong',source.provider));
 for(const a of relevant){const line=el('div');line.append(el('p',a.label+' — '+a.description));if(a.fetchable){const input=el('input');input.placeholder=a.identifier_example;input.setAttribute('aria-label',a.identifier_kind);input.disabled=!canFetch;const b=el('button',canFetch?'Retrieve public reference':'Retrieval is off','secondary');b.disabled=!canFetch;
 b.onclick=guard(async()=>{const id=current,roles=snapshot.definition.inputs.filter(r=>r.accepted_artifact_types?.includes(a.artifact_type));if(!input.value.trim())throw Error('Enter a public accession to retrieve.');b.disabled=true;try{const record=await api('/api/sources',{artifact_type:a.artifact_type,identifier:input.value.trim()});const role=el('select');role.setAttribute('aria-label','Adopted reference role');roles.forEach(r=>role.append(new Option(r.label||friendly(r.role),r.role)));const adopt=el('button','Adopt into this analysis');adopt.onclick=guard(()=>exclusive(async()=>{if(current!==id||dirty)throw Error('Return to the original analysis and save parameters before adopting.');await api(`/api/analyses/${id}/adopt`,{role:role.value,acquisition_id:record.acquisition_id});await openCase(id,{internal:true});notice('Reference adopted. Check readiness for this revision.');}));line.append(el('p','Retrieved and hashed. Choose its role in this case.'),role,adopt);}finally{b.disabled=false;}});line.append(input,b);}else line.append(el('p','Supply this evidence as a local file. Automatic retrieval is not supported.','muted'));box.append(line);}boxes.push(box);}
 $('sources').replaceChildren(...boxes);if(!boxes.length)$('sources').append(el('p','This workflow uses attached local evidence.','muted'));
}
(async()=>{try{const session=await api('/api/session');token=session.token;canFetch=session.reference_fetch_enabled;definitions=await api('/api/definitions');sourceRows=await api('/api/sources');$('workflows').replaceChildren(...definitions.map(d=>{const b=el('button',undefined,'workflow');b.dataset.type=d.analysis_type;b.append(el('strong',names[d.analysis_type]||d.title),el('span',d.analysis_type==='membrane_orientation'?'Experimental':d.analysis_type==='sf_csa'?'Qualification references unresolved':'Qualification incomplete'));b.onclick=()=>choose(d.analysis_type);return b;}));choose(selected);await refreshCases();await refreshJobs();setInterval(()=>refreshJobs().catch(e=>notice(e.message,true)),2000);setInterval(updateClocks,1000);}catch(e){notice('Could not connect to the local workbench: '+e.message,true);}})();
